//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Assessments')
export class AssessmentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  bodyChartFront: string;

  @Column('text', { nullable: true })
  bodyChartLeftSide: string;

  @Column('text', { nullable: true })
  bodyChartRightSide: string;

  @Column('text', { nullable: true })
  bodyChartBack: string;

  @Column('real', { nullable: true })
  adjustmentAngles: number;
}
