//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Measurements')
export class MeasurementsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  degrees: number;

  @Column('real', { nullable: true })
  centimeters: number;
}
