//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Notes')
export class NotesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  upperLimb: string;

  @Column('text', { nullable: true })
  spine: string;

  @Column('text', { nullable: true })
  lowerLimb: string;
}
