//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  PatientsList,
  PatientsCreate,
  PatientsEdit,
} from './resources/Patients';
import {
  AssessmentsList,
  AssessmentsCreate,
  AssessmentsEdit,
} from './resources/Assessments';
import {
  MeasurementsList,
  MeasurementsCreate,
  MeasurementsEdit,
} from './resources/Measurements';
import { NotesList, NotesCreate, NotesEdit } from './resources/Notes';
import {
  ExercisesList,
  ExercisesCreate,
  ExercisesEdit,
} from './resources/Exercises';
import PatientsIcon from '@mui/icons-material/Person';
import AssessmentsIcon from '@mui/icons-material/Assessment';
import MeasurementsIcon from '@mui/icons-material/Rule';
import NotesIcon from '@mui/icons-material/Note';
import ExercisesIcon from '@mui/icons-material/FitnessCenter';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/ad828ade7">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Patients"
          options={{ label: 'Patients' }}
          list={PatientsList}
          create={PatientsCreate}
          edit={PatientsEdit}
          recordRepresentation="name"
          icon={PatientsIcon}
        />
        <Resource
          name="Assessments"
          options={{ label: 'Assessments' }}
          list={AssessmentsList}
          create={AssessmentsCreate}
          edit={AssessmentsEdit}
          recordRepresentation="bodyChartFront"
          icon={AssessmentsIcon}
        />
        <Resource
          name="Measurements"
          options={{ label: 'Measurements' }}
          list={MeasurementsList}
          create={MeasurementsCreate}
          edit={MeasurementsEdit}
          recordRepresentation="degrees"
          icon={MeasurementsIcon}
        />
        <Resource
          name="Notes"
          options={{ label: 'Notes' }}
          list={NotesList}
          create={NotesCreate}
          edit={NotesEdit}
          recordRepresentation="upperLimb"
          icon={NotesIcon}
        />
        <Resource
          name="Exercises"
          options={{ label: 'Exercises' }}
          list={ExercisesList}
          create={ExercisesCreate}
          edit={ExercisesEdit}
          recordRepresentation="column1"
          icon={ExercisesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
