//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Patients: {
      name: 'Patients',
      fields: {
        name: 'Name',
        age: 'Age',
        sex: 'Sex',
        occupation: 'Occupation',
        natureOfWork: 'Nature Of Work',
        complianceHistory: 'Compliance History',
        id: 'id',
      },
    },
    Assessments: {
      name: 'Assessments',
      fields: {
        bodyChartFront: 'Body Chart Front',
        bodyChartLeftSide: 'Body Chart Left Side',
        bodyChartRightSide: 'Body Chart Right Side',
        bodyChartBack: 'Body Chart Back',
        adjustmentAngles: 'Adjustment Angles',
        id: 'id',
      },
    },
    Measurements: {
      name: 'Measurements',
      fields: { degrees: 'Degrees', centimeters: 'Centimeters', id: 'id' },
    },
    Notes: {
      name: 'Notes',
      fields: {
        upperLimb: 'Upper Limb',
        spine: 'Spine',
        lowerLimb: 'Lower Limb',
        id: 'id',
      },
    },
    Exercises: {
      name: 'Exercises',
      fields: { column1: 'Column1', column2: 'Column2', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    Patients: {
      name: 'Patients (fr)',
      fields: {
        name: 'Name (fr)',
        age: 'Age (fr)',
        sex: 'Sex (fr)',
        occupation: 'Occupation (fr)',
        natureOfWork: 'Nature Of Work (fr)',
        complianceHistory: 'Compliance History (fr)',
        id: 'id',
      },
    },
    Assessments: {
      name: 'Assessments (fr)',
      fields: {
        bodyChartFront: 'Body Chart Front (fr)',
        bodyChartLeftSide: 'Body Chart Left Side (fr)',
        bodyChartRightSide: 'Body Chart Right Side (fr)',
        bodyChartBack: 'Body Chart Back (fr)',
        adjustmentAngles: 'Adjustment Angles (fr)',
        id: 'id',
      },
    },
    Measurements: {
      name: 'Measurements (fr)',
      fields: {
        degrees: 'Degrees (fr)',
        centimeters: 'Centimeters (fr)',
        id: 'id',
      },
    },
    Notes: {
      name: 'Notes (fr)',
      fields: {
        upperLimb: 'Upper Limb (fr)',
        spine: 'Spine (fr)',
        lowerLimb: 'Lower Limb (fr)',
        id: 'id',
      },
    },
    Exercises: {
      name: 'Exercises (fr)',
      fields: { column1: 'Column1 (fr)', column2: 'Column2 (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
